version: '3.2'

networks:
  mina-net:
    driver: bridge

services:
  daemon:
    image: minaprotocol/mina-daemon-baked:4.1-turbo-pickles-mina757342b-auto811bf26
    environment:
      PASSWORD: ${PASSWORD:-123456}
      WORKER_FEE: ${WORKER_FEE:-1}
      PUBLIC_KEY: ${PUBLIC_KEY}
    volumes:
      - type: bind
        source: ./keys
        target: /keys
        read_only: true
      - "./config:/root/.mina-config"
    command: ["daemon", "-peer-list-file", "/root/.mina-config/peers.txt", "-block-producer-key", "/keys/my_wallet", "-block-producer-password", "$PASSWORD", "-run-snark-worker", "$PUBLIC_KEY", "-snark-worker-fee", "$WORKER_FEE", "-insecure-rest-server", "-snark-worker-parallelism", "8"]
    expose:
      - 8301
      - 8302
      - 8303
      - 8304
      - 3085
    ports:
      - "${PUBLIC_IP:-0.0.0.0}:8302:8302/udp"
      - "${PUBLIC_IP:-0.0.0.0}:8302:8302/tcp"
    networks:
      - mina-net
      
  stopper:
    image: c29r3/snark-stopper
    restart: unless-stopped
    depends_on:
      - daemon
    networks:
      - mina-net
    volumes:
      - ./config/stopper.yml:/mina/config.yml

  stopper-config:
    image: mikefarah/yq
    volumes:
      - ./keys:/keys
      - ./config:/config

